//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektProgramowanieObjektowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class KontaBankowe
    {
        public int Id { get; set; }
        public string Nr_konta { get; set; }
        public string Nazwa_banku { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public double Stan_Konta { get; set; }
    }
}
