//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektProgramowanieObjektowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySafe
    {
        public int Id { get; set; }
        public string Kod_aktywujacy { get; set; }
        public double Wielkosc_doladowania { get; set; }
    }
}
