//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektProgramowanieObjektowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class RozegraneeGry
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CzasRozegrania { get; set; }
        public Nullable<double> WartoscWygranej { get; set; }
        public Nullable<double> PostawionaGotowka { get; set; }
        public string TrafioneLiczby { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public int Id_rozgrywajacego { get; set; }
    
        public virtual Konto Konto { get; set; }
    }
}
