//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektProgramowanieObjektowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wplaty
    {
        public int Id { get; set; }
        public System.DateTime Data_wpłaty { get; set; }
        public double Kwota_wplaty { get; set; }
        public string Sposob_platnosci { get; set; }
        public int ID_wplacajocego { get; set; }
    
        public virtual Konto Konto { get; set; }
    }
}
