//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektProgramowanieObjektowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wyplaty
    {
        public int Id { get; set; }
        public System.DateTime Data_wyplaty { get; set; }
        public double Wielkosc_wyplaty { get; set; }
        public string Nr_konta { get; set; }
        public string Nazwa_banku { get; set; }
        public string Opis { get; set; }
        public int Id_wyplacajacego { get; set; }
    
        public virtual Konto Konto { get; set; }
    }
}
