//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektProgramowanieObjektowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZasadyGry
    {
        public int Id { get; set; }
        public string Mnoznik_Kolory_dodatnie { get; set; }
        public string Mnoznik_Kolory_ujemne { get; set; }
        public string Mnoznik_Gry_dodatnie { get; set; }
        public string Mnoznik_Gry_ujemne { get; set; }
        public string Opis_zmiany { get; set; }
        public int Id_pracownika_zmieniajacego { get; set; }
        public Nullable<System.DateTime> Data_zmiany { get; set; }
    
        public virtual Konto Konto { get; set; }
    }
}
